/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInternalSessionMaintenanceRouteImport } from './routes/api/internal/session-maintenance'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalSessionMaintenanceRoute =
  ApiInternalSessionMaintenanceRouteImport.update({
    id: '/api/internal/session-maintenance',
    path: '/api/internal/session-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/internal/session-maintenance': typeof ApiInternalSessionMaintenanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/internal/session-maintenance': typeof ApiInternalSessionMaintenanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/internal/session-maintenance': typeof ApiInternalSessionMaintenanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/internal/session-maintenance'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/internal/session-maintenance'
  id: '__root__' | '/' | '/api/internal/session-maintenance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInternalSessionMaintenanceRoute: typeof ApiInternalSessionMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/session-maintenance': {
      id: '/api/internal/session-maintenance'
      path: '/api/internal/session-maintenance'
      fullPath: '/api/internal/session-maintenance'
      preLoaderRoute: typeof ApiInternalSessionMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInternalSessionMaintenanceRoute: ApiInternalSessionMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
